[language-server.deno-ts]
command = "deno"
args = ["lsp"]
config = { enable = true }

[language-server.nimlangserver]
command = "nimlangserver"

[language-server.emmet-lsp]
command = "emmet-language-server"
args = ["--stdio"]

[language-server.pylsp.config.pylsp]
plugins.black.enabled = true
plugins.ruff.enabled = true
plugins.pyls_mypy.enabled = true
plugins.pyls_mypy.live_mode = true

[[language]]
name = "html"
roots = [".git"]
language-servers = ["emmet-lsp"]

[[language]]
name = "javascript"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "svelte"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "typescript"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "nim"
language-servers = ["nimlangserver"]
formatter = { command = "nimpretty", args = ["${INPUT}"] }

[[language]]
name = "python"
roots = ["pyproject.toml"]
language-servers = ["pylsp"]
